# Generated by Django 4.2.1 on 2023-05-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.PositiveIntegerField()),
                ('page', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Boards',
                'unique_together': {('no', 'page')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.PositiveIntegerField(default=0)),
                ('page', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('section', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='database.board')),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='database.board')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='database.section')),
            ],
        ),
        migrations.CreateModel(
            name='Mp3File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='mp3_files/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp3_files', to='database.board')),
            ],
            options={
                'verbose_name_plural': 'MP3 Files',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='database.question')),
            ],
        ),
    ]
