# Generated by Django 4.2.1 on 2023-05-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0003_player_rename_question_answer_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='file',
            field=models.FileField(upload_to='media/mp3_files/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='', max_length=250, unique=True),
        ),
    ]
