# Generated by Django 4.2.1 on 2023-05-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='', max_length=250),
        ),
    ]
