# Generated by Django 4.2.1 on 2023-05-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_answer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
