# Generated by Django 4.0.5 on 2023-06-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mp3file',
            old_name='file',
            new_name='url',
        ),
    ]
